const USER_ROLES = {
  CUSTOMER: "customer",
  PROVIDER: "provider",
  ADMIN: "admin",
};

const ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
  SUSPENDED: "SUSPENDED",
  DELETED: "DELETED",
};

const PLATFORMS = {
  ANDROID: "ANDROID",
  IOS: "IOS",
  WEB: "WEB",
};

const OTP = {
  LENGTH: 6,
  EXPIRY_SECONDS: 300,
  MAX_ATTEMPTS: 5,
  MAX_REQUESTS_PER_WINDOW: 5,
  RATE_LIMIT_WINDOW: 900,
};

const AUDIT_EVENTS = {
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
  OTP_FAILED: "OTP_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  OTP_RATE_LIMIT_EXCEEDED: "OTP_RATE_LIMIT_EXCEEDED",
  TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED",
};

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUS,
  PLATFORMS,
  OTP,
  AUDIT_EVENTS,
};
