const BOOKING_STATUS = Object.freeze({
    REQUESTED: "REQUESTED",

    SEARCHING_PROVIDER: "SEARCHING_PROVIDER",

    PENDING_PROVIDER_RESPONSE: "PENDING_PROVIDER_RESPONSE",

    PROVIDER_ASSIGNED: "PROVIDER_ASSIGNED",

    PROVIDER_ACCEPTED: "PROVIDER_ACCEPTED",

    ON_THE_WAY: "ON_THE_WAY",

    ARRIVED: "ARRIVED",

    SERVICE_STARTED: "SERVICE_STARTED",

    SERVICE_COMPLETED: "SERVICE_COMPLETED",

    PAYMENT_PENDING: "PAYMENT_PENDING",

    PAID: "PAID",

    COMPLETED: "COMPLETED",

    CANCELLED: "CANCELLED",

    PROVIDER_REJECTED: "PROVIDER_REJECTED",

    PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",

    PROVIDER_NO_SHOW: "PROVIDER_NO_SHOW",

    CUSTOMER_NO_SHOW: "CUSTOMER_NO_SHOW",

    FAILED: "FAILED",

    DISPUTED: "DISPUTED"
});
module.exports = { BOOKING_STATUS };