const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  ON_HOLD: 'ON_HOLD',
  PROCESSING: 'PROCESSING',
  PAID: 'PAID',
  RELEASED: 'RELEASED',
  REFUNDED: 'REFUNDED',
  PARTIAL_REFUNDED: 'PARTIAL_REFUNDED',
  FAILED: 'FAILED'
});

module.exports = { PAYMENT_STATUS };