module.exports = Object.freeze({
  SEARCHING_PROVIDER: "SEARCHING_PROVIDER",
  PENDING_PROVIDER_RESPONSE: "PENDING_PROVIDER_RESPONSE",
  PROVIDER_ACCEPTED: "PROVIDER_ACCEPTED",
  FAILED: "FAILED",
});
